services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: miron
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      PGHOST: localhost
    network_mode: host
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mironn206@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    links:
      - postgres:postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  postgres:
  pgadmin:

volumes:
  postgres:
  pgadmin: