server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  kafka:
    bootstrap-servers: broker:9092
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres_db_carting:5432/carting
    username: miron
    password: root

logging:
  level:
    root: INFO
    org.springframework.core.env: DEBUG