server:
  port: 8020

jwt:
  cookie-token-key: '{"kty":"oct","k":"g3DzsM80Aw74n5yarI3xZw"}'
spring:
  kafka:
    bootstrap-servers: 172.28.141.236:9092
  application:
    name: users
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: miron
    password: root
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org:
      springframework:
        security: DEBUG
      springdoc: TRACE

user-sv:
  groupId: groupId
  topic:
    produces:
      userRegisteredEvent: miron-user-registered-event-carting
      checkBalanceEvent: miron-check-balance-event-result-carting
      sendUserInfoForCheckEvent: miron-send-user-info-event-carting
      returnProductsInCartEventValue: miron-return-products-in-cart-event-carting
    consumes:
      checkBalanceEvent: miron-check-balance-event-user
      changeBalanceEvent: miron-change-balance-event-user
